import type { NextPage } from 'next'
import { getSession, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Account: NextPage = ({ session }: any) => {
  console.log(session);
  
  const { status } = useSession({ required: true });

  if (status === 'authenticated') {
    return <div>
      <p>Welcome, {session.user?.email}</p>
      <p>Welcome,
        <Image src={session.user?.image || ''} height={100} width={100} objectFit='cover' alt='' />
      </p>
      <p>Welcome, {session.user?.name}</p>
      <p>Welcome, {new Date(session.expires).toLocaleString()}</p>
      <Link href="/">
        <a>Home page</a>
      </Link>
      <button onClick={() => signOut()}>Logout</button>
    </div>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Link href="/dangnhap">
          <a>Login page</a>
        </Link>
      </div>

    </div>
  )
}

export const getServerSideProps = async (context: any) => {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: '/dangnhap'
      }
    }
  }
  return {
    props: { session }
  }
}


export default Account;
