import type { NextPage } from 'next'
import { getSession, signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

const Home: NextPage = ({ session }: any) => {
  console.log(session);
  
  const router = useRouter();
  const { status } = useSession();

  const handleSignIn = () => {
    router.push(`/dangnhap?callbackUrl=${router.asPath}`)
  }

  const handleSignOut = () => {
    // signOut({ redirect: true, callbackUrl: '/dangnhap' })
    signOut()
    router.push(`/dangnhap`)
  }

  if (status === 'authenticated') {
    return <div>
      <p>Welcome, {session?.user?.email}</p>
      <Link href="/account">
        <a>Account Page</a>
      </Link>
      <button onClick={handleSignOut}>Logout</button>
    </div>
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <button onClick={handleSignIn}>Login</button>
        <Link href={'/account-client'}>
          <a>Client Page</a>
        </Link>
      </div>

    </div>
  )
}

export const getServerSideProps = async (context: any) => {
  const session = await getSession(context);
  return {
      props: { session }
  }
}


export default Home
